ARG FATE_VERSION=1.6.0
FROM crossflowai/fate_base:${FATE_VERSION}-release
ENV FATE_VERSION 1.6.0
RUN apt-get -qq update && DEBIAN_FRONTEND=noninteractive apt-get -qq -y install --no-install-recommends openjdk-8-jre \
    && apt-get -qq -y autoremove && apt-get autoclean \
    && rm -rf /var/lib/apt/lists/* /var/log/dpkg.log
RUN if [ "$(uname -m)"=="x86_64" ] ; then \
      ln -s java-8-openjdk-amd64 /usr/lib/jvm/java-1.8.0-openjdk ; \
    else \
      ln -s java-8-openjdk-aarch64 /usr/lib/jvm/java-1.8.0-openjdk ; \
    fi
WORKDIR /
COPY files/ /data/projects/fate/
COPY start_*.sh requirements.txt/ /
ENV PYTHONPATH /data/projects/fate/eggroll/python:/data/projects/fate/python
ENV EGGROLL_HOME /data/projects/fate/eggroll
WORKDIR /data/projects/fate/eggroll
ENTRYPOINT ["/usr/bin/tini", "--"]
CMD ["/bin/sh"]
